### ISSUE TITLE
[Suggestion] GUI implementation instead of commands

### ISSUE THREAD

**Issue by theravensrequiem** [Mrcomputer1/SmileyPlayerTrader#1]
I'm trying to turn my server into a command-less experience for my users by tying custom items to commands. I think it would be cool if this plugin used a GUI that is opened with one command to customize their shops instead of requiring them to enter commands.

**Comment by smileycreations15** [comment]
@theravensrequiem This is currently in development.

**Comment by smileycreations15** [comment]
If you have any suggestions, etc. tell them here :)

**Comment by Mrcomputer1** [comment]
I'm going to replace the project card with this issue (so I will re-open the issue and remove duplicate).

**Comment by Mrcomputer1** [comment]
This feature has been added and released in version 1.1.0.

You can download from:
SpigotMC: [here](https://www.spigotmc.org/resources/smiley-player-trader.74063/update?update=320011)
Discord: https://discord.gg/SdM6f7U at [this message](https://discordapp.com/channels/661532592415440906/661567969129922560/682443670330408963)
BukkitDev: [here](https://dev.bukkit.org/projects/smiley-player-trader/files/2889621) (although this may still be "Under Review" and not accessible)
GitHub: [here](https://github.com/Mrcomputer1/SmileyPlayerTrader/releases/tag/v1.1.0)
