### ISSUE TITLE
[BUG] Smiley Player Trader v1.3.0 - Duplicate Item

### ISSUE THREAD

**Issue by pa6324641** [Mrcomputer1/SmileyPlayerTrader#11]
Vidoe for Youtube:
[[BUG] Smiley Player Trader v1.3.0 - Duplicate Item](https://youtu.be/IP5lIyhNxmc)
![https://youtu.be/IP5lIyhNxmc](https://i9.ytimg.com/vi_webp/IP5lIyhNxmc/mqdefault.webp?time=1623609300000&sqp=CNSfmYYG&rs=AOn4CLC3NIhWlJffN20nhDqkg_EKJlsimA)

**Comment by Semisol** [comment]
I have been able to sort of pinpoint this to duplicate item refunding on cancellation.
Will work on a patch pretty soon, thanks for the report!

**Comment by Semisol** [comment]
You may view the release here: [v1.3.1](https://github.com/Mrcomputer1/SmileyPlayerTrader/releases/tag/v1.3.1)
Currently not on Spigot and pending approval on Bukkit.

**Comment by Mrcomputer1** [comment]
Release posted on Spigot. Bukkit still pending approval.
