### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by karomismh** [Mrcomputer1/SmileyPlayerTrader#41]
hi sorry if im not doing this right (i havent logged into github in years) but I do have some questions and suggestions:
- Is there a way to see the full list of all items from every player? (like an auctionhouse)
- Can you make it so the thank you message is only to the seller?
- Is there a way to make it so you can only buy a product a certain amount of times? (ex. only being able to buy a product one time and then automatically hides when it is sold)

Once again, sorry if I am doing this wrong, but thank you.

**Comment by Mrcomputer1** [comment]
> Is there a way to see the full list of all items from every player? (like an auctionhouse)

Currently, there isn't a way. I will probably add that though.

> Can you make it so the thank you message is only to the seller?

I will also add a way to configure that.

> Is there a way to make it so you can only buy a product a certain amount of times? (ex. only being able to buy a product one time and then automatically hides when it is sold)

Again, there isn't really a way to do that currently and I will add a way to do it. Although, if you were to only use the plugin's item storage system and disable the `inventory` and `enderchest` stock locations, you would achieve a similar effect (as items would run out of stock and stop being purchasable).

---

I will probably add those things in a few days.

> hi sorry if im not doing this right (i havent logged into github in years) but I do have some questions and suggestions:
> ...
> Once again, sorry if I am doing this wrong, but thank you.

Don't worry, you did it right.

**Comment by Fosyaaa** [comment]
Bro, i russified big part of SPT, i added it below.
[ru_RU.zip](https://github.com/Mrcomputer1/SmileyPlayerTrader/files/9997549/ru_RU.zip)

**Comment by Mrcomputer1** [comment]
> Bro, i russified big part of SPT, i added it below. (Edited I am Ukrainian, btw, may be i russified it all, i don't know) [ru_RU.zip](https://github.com/Mrcomputer1/SmileyPlayerTrader/files/9997549/ru_RU.zip)

Thanks for the translation, I will add it to the next update (pr #42). Also, I created a separate issue (#43) to remind me to add the translation to that update.

**Comment by Mrcomputer1** [comment]
The update with these features is ready and I am planning to release it after 1.19.3, so I can add support for 1.19.3 if necessary.
