### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Mrcomputer1** [Mrcomputer1/SmileyPlayerTrader#43]
Bro, i russified big part of SPT, i added it below. (Edited I am Ukrainian, btw, may be i russified it all, i don't know)
[ru_RU.zip](https://github.com/Mrcomputer1/SmileyPlayerTrader/files/9997549/ru_RU.zip)

_Originally posted by @Fosyaaa in https://github.com/Mrcomputer1/SmileyPlayerTrader/issues/41#issuecomment-1312754376_

**Comment by Fosyaaa** [comment]
[ru_RU.zip](https://github.com/Mrcomputer1/SmileyPlayerTrader/files/10006591/ru_RU.zip)
Updated one with new auto-thanks function.

**Comment by Mrcomputer1** [comment]
I have added Russian to the plugin now and I am planning to release the version with it after 1.19.3 is released.

A few things:
* A few more new strings have been added since you translated, so for now I have put in the English strings as a placeholder. If you want to translate the new strings before the update is released, I will add them to the plugin. Otherwise, I will just release with the placeholder English strings.
* At some point, I want to add a way to give credit for translations in the plugin (probably via `/spt version` and the translation file itself). For when I get around to adding that and for the change log for this version, what would you like to be credited as? - If I don't get a response, I will just use your GitHub username.

**Comment by Fosyaaa** [comment]
I'll now download it and correct for new ver.
